# If you need Pixie support, uncomment the 4 lines below
# and comment the above CXXFLAGS line
#!/bin/bash


SOQT=NO
RENDERMAN=NO
LIB=

ifeq ($(RENDERMAN),YES)
CXXFLAGS=-g -O2 -Wall -DRENDERMAN
INCLUDE=-I${PIXIEHOME}/include
LIB_INC=${PIXIEHOME}/lib
LIB+=-lri
else
# Compilation Flags (also used for the linking)
CXXFLAGS=-g -O2 -Wall -Werror #-Wno-non-template-friend
endif

# Compiler
#CXX=g++

# Linker
#LINKER=g++

-include $(LIBBIARC)/Makefile.local
