# If you need Pixie support, uncomment the 4 lines below
# and comment the above CXXFLAGS line

RENDERMAN=NO

ifeq ($(RENDERMAN),YES)
CXXFLAGS=-g -O2 -Wall -DRENDERMAN
INCLUDE=-I${PIXIEHOME}/include
LIB_INC=${PIXIEHOME}/lib
LIB=-lri
else
# Compilation Flags (also used for the linking)
CXXFLAGS=-g -O2 -Wall #-Wno-non-template-friend
endif

# Compiler
CXX=g++

# Linker
LINKER=g++

COIN=`coin-config --prefix`
SOQT=`soqt-config --prefix`

ifeq ($(shell hostname -d),epfl.ch)
QT_LIB=/usr/lib/qt-3.3/lib
QT_INC=/usr/lib/qt-3.3/include
else
QT_INC=/usr/include/qt3
QT_LIB=/usr/share/qt3/lib
endif
